version: '3.9'
services:
    db-symfony-csv:
        container_name: db-symfony-csv
        image: mysql:8.0.22
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db-symfony-csv:/var/lib/mysql

    php-symfony-csv:
        container_name: php-symfony-csv
        build:
            context: ./docker/php-fpm
        ports:
            - "${PHP_PORT}:9000"
        volumes:
            - .:/var/www/html
#            - -./docker/php-fpm/php.ini-development:/usr/local/etc/php/php.ini-development
            - ./logs/symfony:/var/www/symfony/var/log:cached
        depends_on:
            - db-symfony-csv
        expose:
            - 9003


    nginx-symfony-csv:
        container_name: nginx-symfony-csv
        image: nginx:stable-alpine
        ports:
            - '8093:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/hosts/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-symfony-csv
            - db-symfony-csv

volumes:
    db-symfony-csv:
